package com.tj720.entity.system.menu;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;
@Entity
@Table(name = "sys_res_auth")
public class ResAuth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_auth.id
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    @Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_auth.role_id
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_auth.function_id
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    private String functionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_auth.function_type
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    private String functionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_auth.sort
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_auth.remark
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_auth.status
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_auth.creator
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_auth.updater
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_auth.create_time
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_auth.update_time
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_auth.ext1
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_auth.ext2
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    private String ext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_auth.ext3
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    private String ext3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_auth.id
     *
     * @return the value of sys_res_auth.id
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_auth.id
     *
     * @param id the value for sys_res_auth.id
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_auth.role_id
     *
     * @return the value of sys_res_auth.role_id
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_auth.role_id
     *
     * @param roleId the value for sys_res_auth.role_id
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_auth.function_id
     *
     * @return the value of sys_res_auth.function_id
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public String getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_auth.function_id
     *
     * @param functionId the value for sys_res_auth.function_id
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public void setFunctionId(String functionId) {
        this.functionId = functionId == null ? null : functionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_auth.function_type
     *
     * @return the value of sys_res_auth.function_type
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public String getFunctionType() {
        return functionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_auth.function_type
     *
     * @param functionType the value for sys_res_auth.function_type
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public void setFunctionType(String functionType) {
        this.functionType = functionType == null ? null : functionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_auth.sort
     *
     * @return the value of sys_res_auth.sort
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_auth.sort
     *
     * @param sort the value for sys_res_auth.sort
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_auth.remark
     *
     * @return the value of sys_res_auth.remark
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_auth.remark
     *
     * @param remark the value for sys_res_auth.remark
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_auth.status
     *
     * @return the value of sys_res_auth.status
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_auth.status
     *
     * @param status the value for sys_res_auth.status
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_auth.creator
     *
     * @return the value of sys_res_auth.creator
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_auth.creator
     *
     * @param creator the value for sys_res_auth.creator
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_auth.updater
     *
     * @return the value of sys_res_auth.updater
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_auth.updater
     *
     * @param updater the value for sys_res_auth.updater
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_auth.create_time
     *
     * @return the value of sys_res_auth.create_time
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_auth.create_time
     *
     * @param createTime the value for sys_res_auth.create_time
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_auth.update_time
     *
     * @return the value of sys_res_auth.update_time
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_auth.update_time
     *
     * @param updateTime the value for sys_res_auth.update_time
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_auth.ext1
     *
     * @return the value of sys_res_auth.ext1
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_auth.ext1
     *
     * @param ext1 the value for sys_res_auth.ext1
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_auth.ext2
     *
     * @return the value of sys_res_auth.ext2
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_auth.ext2
     *
     * @param ext2 the value for sys_res_auth.ext2
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_auth.ext3
     *
     * @return the value of sys_res_auth.ext3
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_auth.ext3
     *
     * @param ext3 the value for sys_res_auth.ext3
     *
     * @mbggenerated Wed Oct 10 15:47:07 CST 2018
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }
}