package com.crk.entity.system.menu;

import java.util.Date;

public class MenuTreeDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.id
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.functionName
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    private String functionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.functionUrl
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    private String functionurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.parentId
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.iconRemark
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    private String iconremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.type
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.creator
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.updater
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.create_time
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.update_time
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.status
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.sort
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.ext1
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.ext2
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    private String ext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.ext3
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    private String ext3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.id
     *
     * @return the value of sys_function.id
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.id
     *
     * @param id the value for sys_function.id
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.functionName
     *
     * @return the value of sys_function.functionName
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public String getFunctionname() {
        return functionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.functionName
     *
     * @param functionname the value for sys_function.functionName
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public void setFunctionname(String functionname) {
        this.functionname = functionname == null ? null : functionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.functionUrl
     *
     * @return the value of sys_function.functionUrl
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public String getFunctionurl() {
        return functionurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.functionUrl
     *
     * @param functionurl the value for sys_function.functionUrl
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public void setFunctionurl(String functionurl) {
        this.functionurl = functionurl == null ? null : functionurl.trim();
    }

    public String getPid() {
        return pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.iconRemark
     *
     * @return the value of sys_function.iconRemark
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public String getIconremark() {
        return iconremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.iconRemark
     *
     * @param iconremark the value for sys_function.iconRemark
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public void setIconremark(String iconremark) {
        this.iconremark = iconremark == null ? null : iconremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.type
     *
     * @return the value of sys_function.type
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.type
     *
     * @param type the value for sys_function.type
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.creator
     *
     * @return the value of sys_function.creator
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.creator
     *
     * @param creator the value for sys_function.creator
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.updater
     *
     * @return the value of sys_function.updater
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.updater
     *
     * @param updater the value for sys_function.updater
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.create_time
     *
     * @return the value of sys_function.create_time
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.create_time
     *
     * @param createTime the value for sys_function.create_time
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.update_time
     *
     * @return the value of sys_function.update_time
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.update_time
     *
     * @param updateTime the value for sys_function.update_time
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.status
     *
     * @return the value of sys_function.status
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.status
     *
     * @param status the value for sys_function.status
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.sort
     *
     * @return the value of sys_function.sort
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.sort
     *
     * @param sort the value for sys_function.sort
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.ext1
     *
     * @return the value of sys_function.ext1
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.ext1
     *
     * @param ext1 the value for sys_function.ext1
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.ext2
     *
     * @return the value of sys_function.ext2
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.ext2
     *
     * @param ext2 the value for sys_function.ext2
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.ext3
     *
     * @return the value of sys_function.ext3
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.ext3
     *
     * @param ext3 the value for sys_function.ext3
     *
     * @mbggenerated Wed Oct 10 16:24:11 CST 2018
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }
}